name: store_stock
description: "An inventory app for a shop"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.2


dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  image_picker: ^1.1.2
  async: ^2.11.0
  image_cropper: ^8.0.2
  sqflite:
  collection: ^1.14.13
  path:
  jiffy: ^6.3.1
  path_provider: ^2.1.4
  intl: ^0.19.0
  shared_preferences: ^2.3.2
  http:
  provider: ^6.1.2
  qrscan: ^0.3.3
  #charts_flutter: ^0.9.0
  fl_chart: ^0.68.0
  get_it: ^7.7.0
  flutter_form_builder: ^9.4.1
  #phone_number: ^2.1.0
  #matrix_gesture_detector: ^0.1.0
  #fab_circular_menu: ^1.0.2
  #week_of_year: ^1.0.1
  #progress_dialog: ^1.2.4
  expandable: ^5.0.1
  expandable_group : ^0.0.8
  #firebase_auth:
  archive: ^3.6.1
  flutter_archive: ^6.0.3
  #rename: ^1.2.0

  #overlay: ^0.0.1

  animate_icons:

  #dropdown_date_picker: ^0.0.3

  draggable_fab: ^0.1.4

  share: ^2.0.4

  email_validator: ^3.0.0

  transparent_image: ^2.0.1

  cached_network_image: ^3.4.1

  flutter_staggered_grid_view: ^0.7.0

  auto_size_text: ^3.0.0

  #image_gallery_saver: ^2.0.3

  flutter_speed_dial: ^7.0.0

  #marquee: ^1.6.1

  states_rebuilder: ^6.4.0

  animator: ^3.3.0

  json_serializable: ^6.8.0

  #flutter_colored_progress_indicators: ^1.2.0

  network_to_file_image: ^6.0.1

  printing: ^5.13.2

  pdf: ^3.11.1

  #flutter_money_formatter: ^0.8.3

  #esc_pos_bluetooth: ^0.2.8

  #esc_pos_printer: 4.0.3

  awesome_snackbar_content: ^0.1.3
  sn_progress_dialog: ^1.1.4
  flutter_charts: ^0.5.2
  fab_circular_menu_plus: ^0.0.2
  share_plus: ^10.0.2
  google_fonts: ^6.2.1
  colorful_circular_progress_indicator: ^0.0.2
  flutter_native_splash: ^2.4.1

flutter_native_splash:
  color: "#FCFBF4"
  image: assets/images/madam_rita.png
  android_gravity: center
  ios_content_mode: center
  android: true
  ios: true
  web: true
  android_12:
    color: "#FCFBF4"
    image: assets/images/madam_rita.png

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^4.0.0

flutter_icons:
  image_path: "assets/images/madam_rita.png"
  android: true
  ios: true

flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  assets:
    - assets/images/
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
